platform :ios, '10.0'
use_frameworks!

target 'Bitcoin Adventurer' do
  pod 'Swinject', '2.6.2'
  pod 'SwinjectAutoregistration', '2.6.1'
  pod 'SwinjectStoryboard', '2.2.0'
  
  target 'Bitcoin Adventurer Tests' do
    pod 'Swinject', '2.6.2'
    pod 'SwinjectAutoregistration', '2.6.1'
  end
  
end

